import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid grid-cols-[1fr_4fr_1fr] grid-rows-[64px_auto] gap-x-4 px-4 pb-4 bg-gray-200 w-screen h-screen antialiased`}
      >
        <div className="col-span-full"></div>
        <aside className="w-full h-full bg-white rounded-2xl"></aside>
        <main className="w-full h-full bg-white rounded-2xl">{children}</main>
        <aside className="w-full h-full bg-white rounded-2xl"></aside>
      </body>
    </html>
  );
}
